apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demoapp
  name: demoapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demoapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demoapp
    spec:
      containers:
      - image: koton00beng/protoapp
        name: protoapp
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: "/mnt/data/files"
          name: demovolume
      volumes:
      - name: demovolume
        persistentVolumeClaim:
          claimName: demopvc
status: {}